name: earnings-nlp
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - nltk>=3.6.0
  - scipy>=1.7.0
  - spacy>=3.0.0
  - pytorch>=1.9.0
  - torchvision
  - torchaudio
  - joblib>=1.1.0
  - plotly>=5.3.0
  - wordcloud>=1.8.1
  - jupyter>=1.0.0
  - pip
  - pip:
    - tmtoolkit>=0.10.0
    - streamlit>=1.10.0
    - gensim>=4.2.0
    - transformers>=4.18.0
    - sentence-transformers>=2.2.0
    - bertopic>=0.12.0
    - umap-learn>=0.5.3
    - hdbscan>=0.8.28
    - textstat>=0.7.3
    - python-dotenv>=0.20.0
    - streamlit-plotly-events>=0.0.6
    - altair>=4.2.0
    - watchdog>=2.1.9  # For streamlit development